version: "3.7"

services:
  web:
    build: .
    ports:
      - ${APP_HTTP_PORT}:5174

  client:
      build:
         args:
           CONTAINER_UID: ${CONTAINER_UID}
           CONTAINER_GID: ${CONTAINER_GID}
         context: .
      restart: always
      volumes:
        - ./:/var/app
      working_dir: /var/app
      entrypoint: yarn run dev




