version: "3.7"

services:
  client:
      build:
         args:
           CONTAINER_UID: ${CONTAINER_UID}
           CONTAINER_GID: ${CONTAINER_GID}
         context: .
      ports:
        - ${APP_HTTP_PORT}:3000
      restart: always
      volumes:
        - ./:/var/app
      working_dir: /var/app
      entrypoint: yarn run dev




